package com.canovate.uploader.core;

public enum UpdateStatusCode {
    THIS_VERSION_CHECK_DONE,
    THIS_VERSION_DELETED,
    ALREADY_CREATED,
    UNKNOWN_EXCEPTION,
    UPDATE_NOT_EXIST,
    UPDATE_IN_PROGRESS,
    SUCCESS,
    CARGOMATIC_ID_EMPTY,
    ID_EMPTY,
    APPLICATION_ID_EMPTY,
    APPLICATION_NOT_EXIST,
    GROUP_NOT_EXIST,
    VERSION_EMPTY,
    GROUP_EXIST,
    WRONG_PAGE_NUMBER,
    WRONG_SIZE,
    WRONG_PARAMS,
    DEVICEAPI_INTERNAL_ERROR,
    DEVICEAPI_NOT_RESPONDING,
    GROUP_ID_EMPTY
}